steps:
  - label: ":bash: Tests"
    plugins:
      docker-compose#v3.9.0:
        run: tests

  - label: ":bash: Shellcheck"
    plugins:
      shellcheck#v1.3.0:
        files:
          - hooks/*

  - label: ":sparkles: Linter"
    plugins:
      plugin-linter#v3.0.0:
        id: gopath-checkout