steps:
  - label: run bats tests
    plugins:
      docker-compose#v2.1.0:
        run: tests
    skip: "No tests yet"

  - label: ":bash: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files:
          - hooks/*

  - label: ":sparkles: Linter"
    plugins:
      plugin-linter#v1.0.0:
        name: golang