steps:
  - label: ":bash: Tests"
    plugins:
      - plugin-tester#v1.0.0: ~

  - label: ":bash: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files:
            - hooks/*

  - label: ":sparkles: Linter"
    plugins:
      - plugin-linter#v3.2.0:
          id: gopath-checkout