steps:
  - label: ":bash: Tests"
    plugins:
      docker-compose#v2.5.1:
        run: tests

  - label: ":bash: Shellcheck"
    plugins:
      shellcheck#v1.1.1:
        files:
          - hooks/*

  - label: ":sparkles: Linter"
    plugins:
      plugin-linter#v2.0.0:
        id: gopath-checkout