steps:
  - label: ":bash: Tests"
    plugins:
      - plugin-tester#v1.1.1: ~

  - label: ":bash: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/*

  - label: ":sparkles: Linter"
    plugins:
      - plugin-linter#v3.3.0:
          id: gopath-checkout