#!/bin/bash

set -eu

if [[ -n "${BUILDKITE_PLUGIN_GOLANG_IMPORT:-}" ]]; then
  echo "~~~ :golang: Setting GOPATH and checkout path"

  # Create a scoped gopath which won't collide with non-plugin checkouts
  export GOPATH="${BUILDKITE_BUILD_CHECKOUT_PATH%/*}/.golang/$BUILDKITE_PIPELINE_SLUG"
  echo "GOPATH=$GOPATH"

  # Now checkout into the correct import location within that gopath
  export BUILDKITE_BUILD_CHECKOUT_PATH="$GOPATH/src/$BUILDKITE_PLUGIN_GOLANG_IMPORT"
  echo "BUILDKITE_BUILD_CHECKOUT_PATH=$BUILDKITE_BUILD_CHECKOUT_PATH"

  # Make sure go get/install binaries are installed in the right place
  export GOBIN="$GOPATH/bin"
  echo "GOBIN=$GOBIN"

  # Add golang bin commands to path
  export PATH="$PATH:$GOBIN"
  echo PATH="$PATH"
else
  echo "+++ :golang: No 'import' option specified"
  exit 1
fi
