#!/bin/bash

set -eu

if [[ ! -z "${BUILDKITE_PLUGIN_GOLANG_IMPORT:-}" ]]; then
	echo "--- :golang: Setting up Golang build environment"
	export GOPATH="$BUILDKITE_BUILD_CHECKOUT_PATH"
	export BUILDKITE_BUILD_CHECKOUT_PATH="$BUILDKITE_BUILD_CHECKOUT_PATH/src/$BUILDKITE_PLUGIN_GOLANG_IMPORT"
else
	echo "+++ :golang: No 'import' option specified"
	env | grep 'BUILDKITE_'
	exit 1
fi
